version = 1

[approve]
auto_approve_usernames = ["dependabot"]

[merge]
automerge_label = "automerge ğŸš€"

[merge.automerge_dependencies]
versions = ["major", "minor", "patch"]
usernames = ["dependabot"]
